CREATE DATABASE bankdb;

CREATE USER achris IDENTIFIED BY 'qwerty';
GRANT ALL PRIVILEGES ON bankdb.* TO achris;

USE bankdb;

CREATE TABLE Accounts (ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(30), Surname VARCHAR(40), 
	Tel VARCHAR(20), email VARCHAR(60), Balance  DECIMAL(20,2) UNSIGNED DEFAULT 0.0, Status CHAR(1) DEFAULT 'A') AUTO_INCREMENT=1000000;
	
DESCRIBE Accounts;